language: node_js

node_js:
- 12.13.0

cache: yarn

script:
    - npm run lint
    - npm run test
    - npm run build

deploy:
    install:
      - npm run build-storybook
    provider: pages
    local_dir: storybook-static
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      tags: true
      branches:
        only:
        - /v(\d)\.(\d)\.(\d)(\-\d)?/