language: node_js

node_js:
- 12.13.0
cache: npm

branches:
  only:
  - master

install: npm ci

script:
    - npm run lint
    - npm run test
    - npm run build
    - npm run build-storybook

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      tags: true