language: node_js

node_js:
- 12.13.0
cache: npm

addons:
  artifacts: true

branches:
  only:
  - master

install: npm ci

script:
    - npm run check-types
    - npm run lint
    - npm run test
    - npm run build
    - npm run build-storybook

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN