language: node_js

node_js:
- 12.13.0
cache: npm

branches:
  only:
  - /v(\d)\.(\d)\.(\d)(\-\d)?/

script:
    - npm run lint
    - npm run test
    - npm run build
    - npm run build-storybook 

deploy:
    provider: pages
    script: npm run build-storybook 
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      tags: true