language: node_js

node_js:
- 12.13.0
cache: npm

branches:
  only:
  - master
  - /v(\d)\.(\d)\.(\d)(\-\d)?/

# install: npm ci

# script:
#     - npm run lint
#     - npm run test
#     - npm run build

deploy:
    provider: pages
    script: 
      - npm ci
      - npm run build-storybook 
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    on:
      tags: true